### ISSUE TITLE
Docker plugin is missing LoadPlugin line

### ISSUE THREAD

**Issue by gargath** [librato/puppet-librato#2]
My manifest:
```puppet
class { 'librato':
  email   => '[redacted]',
  token   => '[redacted]',
  require => [ Class['apt::update'], Class['docker'] ],
}

class { 'librato::logging':
  require => Class['librato'],
}

class { 'librato::docker':
  require => [ Class['librato'], Class['docker'] ],
}
```

This works in so far as collectd gets installed and /opt/collectd/etc/collectd.conf.d/docker.conf is created.
The contents:
```
  Exec "nobody" "/opt/collectd/share/collectd/collectd-docker.py" "http://localhost:2735"
```

This silently fails and no metrics are collected.
The solution for me was to add `LoadPlugin` to the file like so:

```
LoadPlugin exec
<Plugin exec>
  Exec "nobody" "/opt/collectd/share/collectd/collectd-docker.py" "http://localhost:2735"
</Plugin>
```
Now metrics are emitted as expected.

Why did the module not take care of this?

**Comment by mjulian** [comment]
Very sorry about that--total oversight on my part. I've fixed this in #4 today.
